---
webui_url: http://213.224.31.105:24035
webui_installation_path: /workspace/stable-diffusion-webui
model_path: /workspace/stable-diffusion-webui/models/Stable-diffusion
source_model: v1-5-pruned.safetensors
new_model_name: test
new_model_scheduler: ddim
training_steps_per_image: 200
class_images_per_instance_image: 0
save_model_frequency: 0
save_preview_frequency: 0
sanity_sample_prompt: photo of ohwx man by Tomer Hanuka
dataset_directory: /workspace/example-dataset
classification_dataset_directory: /workspace/example-images
instance_token: ''
class_token: ''
instance_prompt: ohwx man
class_prompt: photo of man
sample_image_prompt: photo of ohwx man
number_of_samples_to_generate: 1
generate_ckpt_during_training: False
generate_ckpt_when_training_completes: True
generate_ckpt_when_training_is_canceled: False
