---
webui_url: http://24.65.86.25:40250
webui_installation_path: /workspace/stable-diffusion-webui
model_path: /workspace/stable-diffusion-webui/models/Stable-diffusion
source_model: v1-5-pruned.safetensors
new_model_name: chanel-test
new_model_scheduler: ddim
training_steps_per_image: 200
class_images_per_instance_image: 100
save_model_frequency: 0
save_preview_frequency: 0
sanity_sample_prompt: photo of ohwx woman by Tomer Hanuka
dataset_directory: /workspace/chanel-images
classification_dataset_directory: /workspace/woman-images
instance_token: ''
class_token: ''
instance_prompt: ohwx woman
class_prompt: photo of woman
sample_image_prompt: photo of ohwx woman
number_of_samples_to_generate: 1
generate_ckpt_during_training: False
generate_ckpt_when_training_completes: True
generate_ckpt_when_training_is_canceled: False
